// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Gear.Notifications.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(GearNotificationsContext))]
    [Migration("20190625135418_InitialConfig")]
    partial class InitialConfig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gear.Notifications.Models.BaseModels.Event", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("HtmlEventMarkupId");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Gear.Notifications.Models.BaseModels.HtmlEventMarkup", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("ChangesMarkup")
                        .IsRequired();

                    b.Property<Guid>("EventId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Subtitle")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("HtmlEventMarkups");
                });

            modelBuilder.Entity("Gear.Notifications.Models.BaseModels.NotificationProfile", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("NotificationProfiles");
                });

            modelBuilder.Entity("Gear.Notifications.Models.Helpers.NotificationEvent", b =>
                {
                    b.Property<Guid>("EventId");

                    b.Property<Guid>("NotificationProfileId");

                    b.HasKey("EventId", "NotificationProfileId");

                    b.HasIndex("NotificationProfileId");

                    b.ToTable("NotificationEvents");
                });

            modelBuilder.Entity("Gear.Notifications.Models.Helpers.NotificationUser", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("NotificationProfileId");

                    b.HasKey("UserId", "NotificationProfileId");

                    b.HasIndex("NotificationProfileId");

                    b.ToTable("NotificationUsers");
                });

            modelBuilder.Entity("Gear.Notifications.Models.BaseModels.HtmlEventMarkup", b =>
                {
                    b.HasOne("Gear.Notifications.Models.BaseModels.Event", "Event")
                        .WithOne("HtmlEventMarkup")
                        .HasForeignKey("Gear.Notifications.Models.BaseModels.HtmlEventMarkup", "EventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Gear.Notifications.Models.Helpers.NotificationEvent", b =>
                {
                    b.HasOne("Gear.Notifications.Models.BaseModels.Event", "Event")
                        .WithMany("NotificationEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Gear.Notifications.Models.BaseModels.NotificationProfile", "NotificationProfile")
                        .WithMany("NotificationEvents")
                        .HasForeignKey("NotificationProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Gear.Notifications.Models.Helpers.NotificationUser", b =>
                {
                    b.HasOne("Gear.Notifications.Models.BaseModels.NotificationProfile", "NotificationProfile")
                        .WithMany("NotificationUsers")
                        .HasForeignKey("NotificationProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
